application.url=https://www.google.com?q=stg

# API Testing configuration - Staging Environment
api.base.url=https://api-staging.example.com
api.log.request=true
api.log.response=true
api.auth.token=stg-sample-token
api.connection.timeout=12000
api.read.timeout=35000
api.retry.max=2
api.retry.delay=1500